adding zrangewithscores to the obiwan-core
tolitius/obiwan pull request #6
Opened 2023-08-25 10:06 UTC by HariprasathSankaraiyan

<img width="568" alt="image" src="https://github.com/tolitius/obiwan/assets/37661954/31ef4acf-3051-412f-a5e2-d5c82b0ee36e">

2023-08-25 17:56 UTC, tolitius requested changes

2023-08-25 17:56 UTC, tolitius commented on src/obiwan/core.clj
> +
let's move this to [obiwan.commands](https://github.com/tolitius/obiwan/blob/master/src/obiwan/commands.clj)

2023-08-25 17:56 UTC, tolitius commented on src/obiwan/core.clj
> +(defn zrangewithscores [^UnifiedJedis redis k zmin zmax]
`zrange-with-scores`

2023-08-27 17:49 UTC, HariprasathSankaraiyan commented on src/obiwan/core.clj
> +(defn zrangewithscores [^UnifiedJedis redis k zmin zmax]
fixed @tolitius

2023-08-28 14:01 UTC, merged